### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by wlblount** [bpsmith/tia#2]
sorry to contact you like this but is there any way to directly contact you about getting some general help on this module.  Bill

**Comment by bpsmith** [comment]
Sure what can I help you with?

**Comment by ikemblem** [comment]
Hi, thanks for the great library. I saw that you added overrides recently to the bbg requests but I haven't been able to figure out how to use them. Would you mind giving an example if you have a moment?

**Comment by Vjp33** [comment]
I'm not sure if this helps you, but this is how was able to use overrides.

from tia.bbg import LocalTerminal

Data = LocalTerminal.get_historical(tickers, ['BEST_EPS'], start=startdate, end=enddate,BEST_FPERIOD_OVERRIDE='BF',period='MONTHLY').as_frame()

Where I specify tickers, startedate, and enddate earlier on in the code. Let me know if this helps. 
Note that the code should all be on one line.
