### ISSUE TITLE
Imported tia in 2.7 - but issues in both jupyter and ipython

### ISSUE THREAD

**Issue by MichJim** [bpsmith/tia#27]
Changed the environment from 3.0 to 2.7

Opened a new jupyter notebook, but got this error
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-fe02432434a8> in <module>()
----> 1 import tia.bbg.datamgr as dm

ImportError: No module named tia.bbg.datamgr

so thought would try in Ipython

and got an error message 'No module names blpapi'

I am logged into bloomberg - is there something else I should install to get it working

**Comment by MichJim** [comment]
re installed Python 2.7, re installed tia via $ pip install tia, also log into bloomberg on the same pc, but still getting the same error message that there is 'No Module names tia.bbg etc'...look around the site and try the tia.dataanalysis, but get the same error....

Any way that I can check that tia is installed correctly  - I am working on a Max OSX.  any help much appreciated

**Comment by shaunvxc** [comment]
I'm having the same issue... were you able to resolve this @MichJim ?

**Comment by MichJim** [comment]
Sadly I wasn't, and was not able to use it - let me dig out the advice I received and I'll post it here - may be of use

**Comment by MichJim** [comment]
Actually found the answer - it is because the bloomberg is remote.  I ended up downloading the data into and excel spread, saving as a csv/ txt file and imported like that
