### ISSUE TITLE
BChain function

### ISSUE THREAD

**Issue by tryfonch** [bpsmith/tia#42]
Does this library support the BChain function? If not is it going to be updated?

**Comment by bpsmith** [comment]
What’s bchain? Sorry but have been off Bloomberg for a while but now back. If there is an example or documentation then please forward.

**Comment by tryfonch** [comment]
I think this function was introduced  Nov '16. What I do in excel is I click on the Bloomberg ribbon and there exist a button called Function builder. A pop up will show up and there you select the function you want, in my case BChain (you will see there BDH, BDP, BDS, BCurve, BCurveFWD etc)

After you choose BChain you select ticker, "Chain Type" where you choose between Bonds, Loans and Options and lastly any additional attributes like Loan_Typ. 


Unfortunately the only documentation regarding this function was on Terminal's Helpdesk and I cannot export that.

**Comment by tryfonch** [comment]
There is no way to implement it yet therefore I close this post.
