### ISSUE TITLE
WARN blpapi_platformcontroller Connectivity Issue

### ISSUE THREAD

**Issue by BoonAtARJ** [bpsmith/tia#43]
I am using python 3.5 and has been working fine up until Tuesday night when I started to get the following messages after every ticker + tag combination request:

> 14JUN2018_10:32:57.411 6396:17504 WARN blpapi_platformcontroller.cpp:347 blpapi.session.platformcontroller.{5} Connectivity restored. 

I contacted Bloomberg and was told that its alright to ignore because its just a warning message. 
Was also told to uninstall and reinstall (didn't fix the issue). 

I can still get data but am wondering how to solve/approach this warning issue? Has anybody gotten the same warning messages repeatedly within the last couple of days?

**Comment by jason79** [comment]
i'm getting the same thing. only recently though (early Dec). I'm using python 2.7. 

Have you been able to suppress the message or fix it?

**Comment by BoonAtARJ** [comment]
Nope, learned to live with it. In a way, its assuring to know the program isn't freezing on me - haha!

I ordered a new PC and will me switching over the next 2 - 3 weeks. Will let you know if I run into the same problem. If you find a way to suppress it please let me know!

**Comment by BoonAtARJ** [comment]
Update - successfully got it to work on my new desktop. 

Got everything to work with no warning messages.

Am now running on py 3.7 which required me to install bloomberg's C++ experimental release (found here [https://www.bloomberg.com/professional/support/api-library/](url) and their latest SDK (WAPI in the terminal <GO>, desktop API download, etc. etc. that was updated as of 10/2018).

Guess the answer to this is to keep everything up to date?
